#!/usr/bin/env bash
set -euo pipefail

hooks=(
  "microservices/api/.githooks/pre-push"
  "microservices/frontend/.githooks/pre-push"
  "microservices/kafka-consumer/.githooks/pre-push"
)

for hook in "${hooks[@]}"; do
  if [[ -x "$hook" ]]; then
    "$hook"
  fi
done
