spring.application.name=api
server.port=8081
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:meshops_api;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.sql.init.mode=${SPRING_SQL_INIT_MODE:always}
