spring.application.name=api
server.port=8081
spring.datasource.url=jdbc:h2:mem:meshops_api;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.mode=always
